# Generated by Django 2.0.3 on 2018-03-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'get_latest_by': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Place')),
                ('building', models.CharField(help_text="Building's name", max_length=64)),
                ('reference', models.CharField(help_text='Give a short identifier tag to this apartment', max_length=16)),
                ('number', models.SmallIntegerField(help_text='Apartment number')),
                ('floor', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['reference', 'building'],
            },
            bases=('api.place',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Place')),
                ('civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('M. Mme', 'Monsieur et Madame'), ('SCI', 'Société Civile')], max_length=16)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            bases=('api.place',),
        ),
        migrations.AddField(
            model_name='bill',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Apartment'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='persons',
            field=models.ManyToManyField(to='api.Person'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='ticket',
            order_with_respect_to='apartment',
        ),
    ]
