# Generated by Django 2.0.3 on 2018-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.TextField(default='', help_text='The full address', max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='zip_code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
